version: "3.7"
services:
  #api container
  api:
    image: londuso/fastapi
    depends_on:
      - db
    
    ports:
      - "80:8000"
      
    #command: uvicorn --host=0.0.0.0 application.main:app --port=8000

    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ALGORITHIM=${ALGORITHIM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

   # OR
   # env_file:
   #     - ./.env
   

  #Database container
  db:
    image: postgres #the base image found in docker hub site
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - postgres_db:/var/lib/postgresql/data

# Global volumes  
volumes:
 postgres_db: