name: Build and Deploy

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2 # actions/checkout@v2 command pulls our code
      - name: Install Python 3.9
        uses: actions/setup-python@v2 # this installs python
        with:
          python-version: "3.9"
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install All Depedencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: | # the pipe allows you run muliple commands for this case[pip install pytest and pytest -v -s]
         pip install pytest-github-actions-annotate-failures
         pytest
        