name: Build and Deploy

on: [push, pull_request]

jobs:
  job1:
    #option 1 of pulling environments variables
    environment:
      name: testing # pulls the environment variables from github {setting>>>environments section}

    #option 2 of pulling environment variables
    env:
        DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
        DATABASE_PORT: ${{secrets.DATABASE_PORT}}
        DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
        DATABASE_NAME: ${{secrets.DATABASE_NAME}}
        DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
        JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
        ALGORITHIM: ${{secrets.ALGORITHIM}}
        ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2 # actions/checkout@v2 command pulls our code
      - name: Install Python 3.9
        uses: actions/setup-python@v2 # this installs python
        with:
          python-version: "3.9"
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install All Depedencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: | 
         pip install -e .
         pip install pytest
         pytest
        