name: Build and Deploy

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2 # actions/checkout@v2 command pulls our code
      - name: Install Python 3.9
        uses: actions/setup-python@v2 # this installs python
        with:
          python-version: "3.9"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install All Depedencies
        run: pip install -r requirements.txt
        